## Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
# set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin "catppuccin/tmux#v2.1.3"


# set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
# set -g @vim_navigator_mapping_right "C-Right C-l"
# set -g @vim_navigator_mapping_up "C-k"
# set -g @vim_navigator_mapping_down "C-j"

# Mouse support
set -g mouse on
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_text "#{window_name}:#{pane_current_path}"
set -g @catppuccin_window_current_text "#{window_name}:#{pane_current_path}"
# Make the status line more pleasant.
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '
set -g status-right-length 100
run ~/.tmux/plugins/catppuccin/catppuccin.tmux

# set -g @catppuccin_window_status_style "rounded"
## TODO: also put path on the name
# set -g @catppuccin_window_current_text "#{window_name}" # required for WSL
# set -g @catppuccin_window_text "#{window_name}"

# # Start windows/panes at 1 (not 0)
# set -g base-index 1
# setw -g pane-base-index 1
#
# # Status bar (match Powerlevel10k aesthetics)
# set -g status-right "#[fg=cyan,bold]%H:%M"
# set -g status-style "fg=#586e75,bg=#fdf6e3"  # Solarized light-like
# set -g window-status-current-style "fg=red,bold"

# Hyprland-compatible window management
bind -n M-n new-window     # ALT + n: New window
bind -n M-w kill-window    # ALT + w: Close window
bind -n M-Left previous-window  # ALT + Left: Prev window
bind -n M-Right next-window     # ALT + Right: Next window

# Load TPM (Tmux Plugin Manager)
run-shell ~/.tmux/plugins/tpm/tpm
