## Binding Ctrl+Backslash as prefix
set -g prefix C-\\
unbind C-b
bind C-\\ send-prefix
## Binding Hyprland-compatible window management
bind -n M-n new-window                                    # ALT + n: New window
bind -n M-w kill-window                                   # ALT + w: Close window
bind -n M-Left previous-window                            # ALT + Left: Prev window
bind -n M-Right next-window                               # ALT + Right: Next window
bind -n M-h previous-window                               # ALT + h: Prev window
bind -n M-l next-window                                   # ALT + l: Next window
bind-key -n M-= swap-window -t +1 \; select-window -t:+1  # ALT + -: "move" window to next index
bind-key -n M-- swap-window -t -1 \; select-window -t:-1  # ALT + -: "move" window to previous index

## Start windows/panes at 1 (not 0)
set -g base-index 1
setw -g pane-base-index 1
# Focus and terminal colors (neovim required)
set-option -g focus-events on
# For VI selection and yank
set-window-option -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# True color support
set-option -a terminal-features 'xterm-256color:RGB'

## Mouse support
set -g mouse on

## Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_text "#{window_name}:#{s|^$HOME|~|:pane_current_path}"
set -g @catppuccin_window_current_text "#{window_name}:#{s|^$HOME|~|:pane_current_path}"
# Make the status line more pleasant.
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '
set -g status-right-length 100
run ~/.tmux/plugins/catppuccin/catppuccin.tmux


## Load TPM (Tmux Plugin Manager)
run-shell ~/.tmux/plugins/tpm/tpm
## TPM commands:
# prefix + I : Install plugins
# prefix + U: Update plugins
# prefix + alt + u: Remove/uninstall plugins not on here
